### ISSUE TITLE
Custom Model Data on RV Items

### ISSUE THREAD

**Issue by knniDE** [aematsubara/RealisticVillagers#27]
Would be cool to be able to configure custom model data for e.g. a resource pack in the config. <3

**Comment by aematsubara** [comment]
You can already do that with the plugin, adding `model-data` to an item. For example:

```
chat:
    slot: 2, 2
    model-data: 123
    material: PAPER
    display-name: "&aChat"
    lore:
      - "&7Click to chat with this villager."
```
