### ISSUE TITLE
[REQUEST * SUGGESTION] Player Head materials

### ISSUE THREAD

**Issue by MarkinhosMLP** [aematsubara/RealisticVillagers#28]
make us able to use a player head material with the npc/villager skin in it!! useful for custom guis and stuff like that

**Comment by aematsubara** [comment]
You can already use custom skull textures in GUIs, setting the `material` to **PLAYER_HEAD** and then using `url`. For example:
```
gift:
    slot: 5, 3
    url: 5726d9d0632e40bda5bcf65839ba2cc98a87bd619c53adf00310d6fc71f042b5
    material: PLAYER_HEAD
    display-name: "&aGift"
    lore:
      - "&7Click to give a gift to this villager."
```
Is this what you're asking? Or do you want to use the texture of the current villager in the main GUI?
